import assert from "node:assert/strict";
import { test } from "node:test";
import { applySuggestions, attributionLines, checkCommits, commitsAgentText, subjectProblem } from "../src/commits.ts";
import type { Pr } from "../src/github.ts";

const types = ["feat", "fix", "docs", "chore", "bench"];

test("subjectProblem accepts conventional subjects and git's own merge and revert subjects", () => {
  for (const ok of [
    "feat: add a thing",
    "fix(coro): publish task completion",
    "feat(index)!: drop the old key layout",
    "bench: the engine against pandas",
    "Merge branch 'feat/x' into 'develop'",
    'Revert "feat: add a thing"',
  ]) {
    assert.equal(subjectProblem(ok, types), null, ok);
  }
});

test("subjectProblem names what is wrong", () => {
  assert.match(subjectProblem("Update LICENSE", types) ?? "", /not `type\(scope\): description`/);
  assert.match(subjectProblem("feature: add a thing", types) ?? "", /unknown type `feature`/);
  assert.match(subjectProblem("fix!(coro): leak", types) ?? "", /goes after the scope/);
  assert.match(subjectProblem("fix:no space", types) ?? "", /not `type/);
});

test("checkCommits checks the PR title and every commit, and is off without a policy", () => {
  const pr = {
    title: "Add replay",
    body: "",
    html_url: "https://github.com/o/r/pull/7",
    commits: [
      { sha: "a".repeat(40), subject: "feat: add replay", message: "feat: add replay" },
      { sha: "b".repeat(40), subject: "WIP", message: "WIP" },
    ],
  } as Pr;
  assert.deepEqual(checkCommits(pr, undefined), []);
  const issues = checkCommits(pr, { types, severity: "P1" });
  assert.deepEqual(
    issues.map((i) => [i.where, i.severity]),
    [
      ["PR title", "P1"],
      ["bbbbbbb", "P1"],
    ],
  );
  assert.equal(issues[1].url, `https://github.com/o/r/pull/7/commits/${"b".repeat(40)}`);
});

test("applySuggestions keeps only a suggestion that passes the check", () => {
  const issue = (where: string) => ({ where, subject: "x", problem: "p", severity: "P1" as const, url: "u" });
  const out = applySuggestions(
    [issue("PR title"), issue("aaaaaaa"), issue("bbbbbbb")],
    [
      { where: "PR title", subject: "feat(prov): add the provenance view" },
      { where: "aaaaaaa", subject: "Added things" },
    ],
    types,
  );
  assert.deepEqual(
    out.map((c) => c.suggested),
    ["feat(prov): add the provenance view", undefined, undefined],
  );
});

test("attributionLines finds AI trailers and badges, and keeps human co-authors", () => {
  assert.deepEqual(attributionLines("feat: x\n\nbody\n\nCo-authored-by: Claude <noreply@anthropic.com>"), [
    "Co-authored-by: Claude <noreply@anthropic.com>",
  ]);
  assert.deepEqual(attributionLines("fix: y\n\nCo-authored-by: Jane Doe <jane@example.org>"), []);
  assert.deepEqual(attributionLines("fix: y\n\nGenerated with Claude Code\nAssisted-by: rsrobo"), [
    "Generated with Claude Code",
    "Assisted-by: rsrobo",
  ]);
  assert.deepEqual(attributionLines("fix: y\n\nMade with care"), []);
});

test("checkCommits reports attribution in a commit and in the PR body, and the agent text says what to delete", () => {
  const pr = {
    title: "feat: add replay",
    body: "Adds replay.\n\nGenerated by Copilot",
    html_url: "https://github.com/o/r/pull/7",
    head_ref: "feat",
    head_repo: "o/r",
    base: "c".repeat(40),
    commits: [
      {
        sha: "a".repeat(40),
        subject: "feat: add replay",
        message: "feat: add replay\n\nCo-authored-by: Claude <noreply@anthropic.com>",
      },
    ],
  } as Pr;
  const issues = checkCommits(pr, { types, severity: "P1" });
  assert.deepEqual(
    issues.map((i) => [i.where, i.problem]),
    [
      ["PR body", "AI attribution: `Generated by Copilot`"],
      ["aaaaaaa", "AI attribution: `Co-authored-by: Claude <noreply@anthropic.com>`"],
    ],
  );
  const text = commitsAgentText(pr, issues);
  assert.match(text, /aaaaaaa: delete these lines from the message: "Co-authored-by: Claude <noreply@anthropic.com>"/);
  assert.match(text, /Delete these lines from the pull request description: "Generated by Copilot"\./);
  assert.doesNotMatch(text, /PR body:/);
});
